### ISSUE TITLE
Getting `TRUE` for 2001 and after, download error for earlier years 

### ISSUE THREAD

**Issue by Ljupch0** [JYProjs/patentr#27]
Hi devs,

Thanks for the work and package.

For more recent years I am getting the TRUE placeholder and no data is downloading.

I tried running the examples and other years before 2001, and it attempts to download but I am getting this error:

```
Error in utils::download.file(url = curr_url, destfile = dest_file) : 
  cannot open URL 'https://bulkdata.uspto.gov/data/patent/grant/redbook/fulltext/2001/pftaps20010102_wk01.zip'
In addition: Warning message:
In utils::download.file(url = curr_url, destfile = dest_file) :
  InternetOpenUrl failed: 'The certificate authority is invalid or incorrect'
```
Probably can't verify the SSL of the USPTO website. 

On an unrelated note, is there a way to download the patent data connected to a certain inventor or company instead of going by week?

**Comment by rrrlw** [comment]
Thank you for opening this issue. Are you having trouble with the CRAN version or GitHub version of patentr?


> On an unrelated note, is there a way to download the patent data connected to a certain inventor or company instead of going by week?

Unfortunately, since the bulk data is provided as 1 file per week of filed patents, the best way to select patents for a specific inventor or assignee would be to download all the data, then filter for that inventor or assignee.

**Comment by Ljupch0** [comment]
Hi thank you, I'm on the cran version.

**Comment by rrrlw** [comment]
Thank you for bringing up this issue @Ljupch0. I believe it has been fixed in the development version, can you install using the lines below and confirm?

```r
# use either of the two lines
devtools::install_github("JYProjs/patentr")
remotes::install_github("JYProjs/patentr")
```
